package com.example.oraclestat;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SelectableCustomTable extends VerticalLayout {
	protected Table tableData;
	protected HorizontalSplitPanel test;
	protected ListSelect listOwners;
	protected TabSheet detailTabs;
	protected Table tableDetailsTable;
	protected Table tableDetailsTBSpaces;

	public SelectableCustomTable() {
		Design.read(this);
	}
}
